"""Markdown report output."""

from __future__ import annotations

from pathlib import Path

from ..models import AnalysisResult, BatchAnalysisResult


class MarkdownReporter:
    """Export analysis results as Markdown."""

    def session_to_markdown(self, result: AnalysisResult) -> str:
        """Render a single session as Markdown."""
        s = result.session
        lines = [
            f"# Session: {s.session_id}",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| Framework | {s.framework.value} |",
            f"| Model | {s.model or '-'} |",
            f"| Outcome | {s.outcome.value} |",
            f"| Events | {len(s.events)} |",
            f"| Tokens | {s.total_tokens:,} |" if s.total_tokens else "",
            f"| Risk Score | **{result.risk_score:.0%}** |",
            "",
        ]

        if not result.failures:
            lines.append("> No failures detected.")
        else:
            lines.append(
                f"## Failures ({len(result.failures)})"
            )
            lines.append("")
            lines.append(
                "| # | Severity | Category | Subcategory"
                " | Description | Confidence |"
            )
            lines.append("|---|---|---|---|---|---|")
            for i, f in enumerate(result.failures, 1):
                desc = f.description[:80].replace("|", "\\|")
                lines.append(
                    f"| {i} | {f.severity.value.upper()}"
                    f" | {f.category.value}"
                    f" | {f.subcategory.value}"
                    f" | {desc}"
                    f" | {f.confidence:.0%} |"
                )

            # Evidence
            lines.append("")
            lines.append("### Evidence")
            lines.append("")
            for i, f in enumerate(result.failures[:5], 1):
                if f.evidence:
                    lines.append(f"**#{i} {f.subcategory.value}:**")
                    for ev in f.evidence[:2]:
                        cleaned = ev[:150].replace("`", "'")
                        lines.append(f"- `{cleaned}`")
                    lines.append("")

        return "\n".join(line for line in lines if line is not None)

    def batch_to_markdown(self, batch: BatchAnalysisResult) -> str:
        """Render batch results as Markdown."""
        total_failures = sum(
            len(r.failures) for r in batch.results
        )
        fail_rate = (
            f"{batch.failed_sessions / batch.total_sessions:.0%}"
            if batch.total_sessions > 0
            else "0%"
        )

        lines = [
            "# Agent Failure Analysis Report",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| Total Sessions | {batch.total_sessions} |",
            f"| Failed Sessions | {batch.failed_sessions} |",
            f"| Total Failures | {total_failures} |",
            f"| Failure Rate | {fail_rate} |",
            "",
        ]

        # Category breakdown
        if batch.category_counts:
            lines.append("## Failures by Category")
            lines.append("")
            lines.append("| Category | Count |")
            lines.append("|---|---|")
            for cat, cnt in sorted(
                batch.category_counts.items(),
                key=lambda x: x[1],
                reverse=True,
            ):
                lines.append(f"| {cat} | {cnt} |")
            lines.append("")

        # Top failures
        if batch.top_failures:
            lines.append("## Top Failure Types")
            lines.append("")
            lines.append("| # | Subcategory | Count |")
            lines.append("|---|---|---|")
            for i, (sub, cnt) in enumerate(
                batch.top_failures[:10], 1
            ):
                lines.append(f"| {i} | {sub} | {cnt} |")
            lines.append("")

        # Per-session details
        risky = sorted(
            batch.results,
            key=lambda r: r.risk_score,
            reverse=True,
        )
        for r in risky[:10]:
            if r.failures:
                lines.append("---")
                lines.append("")
                lines.append(self.session_to_markdown(r))
                lines.append("")

        lines.append(
            "*Generated by Agent Failure Analyzer*"
        )
        return "\n".join(lines)

    def write_batch(
        self, batch: BatchAnalysisResult, path: str | Path
    ) -> None:
        Path(path).write_text(self.batch_to_markdown(batch))

    def write_session(
        self, result: AnalysisResult, path: str | Path
    ) -> None:
        Path(path).write_text(
            self.session_to_markdown(result)
        )
